Section4/alpha-blog/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  get 'pages/about', to: "pages#about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy ]
  get 'signup', to:"users#new"
  resources :users, except: [:new]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete "logout", to:"sessions#destroy"
  resources :categories, except: [:destroy]

end

Section4/alpha-blog/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, length: {minimum: 6, maximum: 100}, presence: true
  validates :description,  presence: true, length: {minimum: 10, maximum: 1000}

end

Section4/alpha-blog/app/models/article_category.rb
class ArticleCategory<ApplicationRecord
  belongs_to :article
  belongs_to :category
end

Section4/alpha-blog/app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
  has_many :article_categories
  has_many :articles, through: :article_categories
end

Section4/alpha-blog/app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  validates :username, presence: true, length: {minimum: 3, maximum: 25}, uniqueness: { case_sensitive: false }

  before_save { self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105},
            uniqueness: { case_sensitive: false },
            format: {with: VALID_EMAIL_REGEX}
  has_secure_password

end

Section4/alpha-blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  #helper_method :current_user, :logged_in?
  #   def current_user
  #     @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  #   end
  #  def logged_in?
  #     puts("User #{current_user}")
  #     puts("#{!!current_user}")
  #     !!current_user
  #   end

  def require_user
    unless logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end



end

Section4/alpha-blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only:[:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def index
    #@articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def create

    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article created successfully"
      redirect_to article_path(@article)
    else
      render 'articles/new'
    end
    #Article.create(params[:article])

  end

  def new
    unless logged_in?
      flash.now[:alert] = "You need be logged in to create a new article"
      render "sessions/new"
    end
    @article =  Article.new
  end

  def show
    #byebug
  end

  def edit

  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article updated successfully"
      redirect_to article_path(@article)
    else
      render "edit"
    end
  end
  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  def set_article

    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end

end

Section4/alpha-blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfylly created";
      redirect_to category_path(Category.last)
    else
      render "new"
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page:3)
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully"
      redirect_to @category
    else
      render "edit"
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end

  end
end

Section4/alpha-blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  def about

  end
end

Section4/alpha-blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully";
      redirect_to user_path(user)
    else
      flash.now[:alert] = "There was something wrong"
      render "new"
    end
  end

  def new

  end

  def destroy
    session[:user_id] = nil
    p session[:user_id]
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

Section4/alpha-blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 2)
  end

  def new
    @user = User.new;
  end

  def create
    @user = User.new(user_params_to_signup)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Alpha Blog #{@user.username}, you have successfully signed up"
      redirect_to articles_path
    else
      @user.email = ""
      render "new"
    end
  end

  def edit
    unless @user
      redirect_to root_path
    end
  end

  def update
    p params
    if @user.update(user_params_to_signup)
      flash[:notice] = "Your account informations was successfully updated"
      redirect_to @user
    else
      render "edit"
    end
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 2)
    unless @user
      redirect_to root_path
    end

  end

  def destroy
    session[:user_id] = nil if @user.id == session[:user_id]
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params_to_signup
    params.require(:user).permit(:email, :username, :password)
  end

  def set_user
    @user = User.find_by_id(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit your own account"
      redirect_to @user
    end
  end


end

Section4/alpha-blog/app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size];
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end



end

Section4/alpha-blog/app/helpers/pages_helper.rb
module PagesHelper
end

Section4/alpha-blog/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    puts("User #{current_user}")
    puts("#{!!current_user}")
    !!current_user
  end
end

Section4/alpha-blog/app/views/articles/_article.html.erb
<div class="row justify-content-center">
  <div class="col-8 ">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header font-italic">
        <% if article.user %>
          by <%= link_to article.user.username, user_path(article.user) %>
        <% end %>
        <% if article.categories.any? %>
          <div class="mt-2">
            <%= render article.categories%>
          </div>
        <%end %>
      </div>
      <div class="card-body">
        <h5 class="card-title "><%=link_to article.title, article_path(article), class: "text-success" %></h5>
        <p class="card-text"><%= truncate(article.description, lenght: 100) %></p>
        <%= link_to  "View", article_path(article.id), method: :get , class: "btn btn-outline-success"%>
        <% if logged_in? && (current_user.admin? || article.user.id == current_user.id) %>
          <%= link_to  "Edit", edit_article_path(article.id), method: :get, class: "btn btn-outline-info" %>
          <%= link_to  "Delete", article_path(article.id), method: :delete, data: {confirm: "Are you sure?"} , class: "btn btn-outline-danger"%>
        <% end %>
      </div>
      <div class="card-footer text-muted">
        <small>Created <%=time_ago_in_words(article.created_at) %></small>
        <small>Edited <%=time_ago_in_words(article.updated_at) %></small>

      </div>
    </div>
  </div>
</div>

Section4/alpha-blog/app/views/articles/_form.html.erb
<div class="container">


  <div class="row justify-content-center ">
    <div class="col-10">
      <%= render "shared/errors" ,obj: @article%>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded" ,local: true) do |f|%>
        <div class="form-group row">
            <%=f.label :title , class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%=f.text_field :title ,class: "form-control shadow rounded", placeholder: "Title of article"%>
          </div>
        </div>
        <div class="form-group row">
          <%=f.label :description , class: "col-2 col-form-label text-light"%><br/>
          <div class="col-10">
          <%=f.text_area :description , rows: 10 ,class: "form-control shadow rounded", placeholder: "Description of article"%>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10 ">
            <%= f.collection_select(:category_ids, Category.all, :id, :name,
                                    { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true ,  class: "custom-select shadow rounded" }) %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%=f.submit  class:"btn btn-outline-light btn-lg"%>
        </div>
      <%end %>
    </div>
    <div class="mb-3">
      <%= link_to "[Cancel and return to articles listing]", articles_path, class: "text-info"  %>
    </div>
  </div>
</div>

Section4/alpha-blog/app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render "form", text_action: "Edit" %>

Section4/alpha-blog/app/views/articles/index.html.erb
<h1 class="text-center mt-4 ">Listing all Articles</h1>
<div class="flickr_pagination mb-4">
  <div class="page_info">
    <%= page_entries_info @articles %>
  </div>
  <%= will_paginate(@articles, :container => false) %>
</div>

<% @articles.each do |article| %>
  <%= render "articles/article", article: article %>
<% end %>

<div>
  <p>
    <%= link_to "Create new Article", new_article_path %>
  </p>
</div>

<div class="flickr_pagination mb-4">
  <div class="page_info">
    <%= page_entries_info @articles %>
  </div>
  <%= will_paginate(@articles, :container => false) %>
</div>


<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Title</th>-->
<!--      <th>Description</th>-->
<!--      <th>Actions</th>-->
<!--    </tr>-->

<!--  </thead>-->
<!--  <tbody>-->
  <%# @articles.each do |article| %>
<!--    <tr>-->
<!--      <td><%#= article.title %></td>-->
<!--      <td><%#= article.description %></td>-->
<!--      <td><%#= link_to  "Show", article_path(article.id), method: :get %></td>-->
<!--      <td><%#= link_to  "Edit", edit_article_path(article.id), method: :get %></td>-->
<!--      <td><%#= link_to  "Delete", article_path(article.id), method: :delete, data: {confirm: "Are you sure?"} %></td>-->

<!--    </tr>-->
  <%# end %>
<!--  </tbody>-->
<!--</table>-->

Section4/alpha-blog/app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new Article</h1>

<%=render "form" %>

Section4/alpha-blog/app/views/articles/show.html.erb
<h2 class="text-center mt-4 "><%=@article.title %></h2>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-8 ">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= @article.user.username if @article.user%>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          <% if @article.categories.any? %>
           <div class="mt-2">
              <%= render @article.categories%>
           </div>
          <%end %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <% if logged_in? && @article.user == current_user %>
            <%= link_to  "Edit", edit_article_path(@article.id), method: :get, class: "btn btn-outline-info" %>
            <%= link_to  "Delete", article_path(@article.id), method: :delete, data: {confirm: "Are you sure?"} , class: "btn btn-outline-danger"%>
          <%end %>
        </div>
        <div class="card-footer text-muted">
          <smal>Created <%=time_ago_in_words(@article.created_at) %></smal>
          <smal>Edited <%=time_ago_in_words(@article.updated_at) %></smal>
        </div>
      </div>
    </div>
  </div>
</div>

<!--<h1>Showing article details</h1>-->
<!--<p>-->
<!--  <strong>Title: <%#= @article.title%></strong>-->
<!--  <br>-->
<!--  <strong>Description: <%#= @article.description%></strong>-->
<!--</p>-->

<%#= link_to "Edit", edit_article_path(@article) %>
<%#= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %>
<%#= link_to "Return to article list", articles_path(@article) %>

Section4/alpha-blog/app/views/categories/_category-comp.html.erb
<div class="row justify-content-center">
  <div class="col-4 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-body">
        <h5 class="card-title mt-4"><%=link_to category.name, category_path(category), class: "text-success" %></h5>
        <p class="card-text"><%= pluralize(category.articles.count, "category") %></p>
      </div>
      <div class="card-footer text-muted">
        <small>Created <%=time_ago_in_words(category.created_at) %></small>
        <small>Edited <%=time_ago_in_words(category.updated_at) %></small>

      </div>
    </div>
  </div>
</div>

Section4/alpha-blog/app/views/categories/_category.html.erb
<%=link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

Section4/alpha-blog/app/views/categories/_form.html.erb
<div class="container">


  <div class="row justify-content-center ">
    <div class="col-10">
      <%= render "shared/errors", obj: @category %>
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded" ,local: true) do |f|%>
        <div class="form-group row">
          <%=f.label :name,  "Category name", class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%=f.text_field :name ,class: "form-control shadow rounded", placeholder: "Enter your username"%>
          </div>

        </div>

        <div class="form-group row justify-content-center">
          <%=f.submit  class:"btn btn-outline-light btn-lg"%>
        </div>
      <%end %>
    </div>
    <div class="mb-3">
      <%= link_to "[Cancel and return to categories listing]", categories_path, class: "text-info"  %>
    </div>
  </div>
</div>

Section4/alpha-blog/app/views/categories/edit.html.erb
<h1 class="text-center mt-4"> Edit category</h1>
<%= render "form" %>

Section4/alpha-blog/app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="flickr_pagination mb-4">
  <div class="page_info">
    <%= page_entries_info @categories %>
  </div>
  <%= will_paginate(@categories, :container => false) %>
</div>
<% @categories.each do |category| %>
  <%= render "category-comp", category: category %>
<% end %>


<div class="flickr_pagination mb-4">
  <div class="page_info">
    <%= page_entries_info @categories %>
  </div>
  <%= will_paginate(@categories, :container => false) %>
</div>

Section4/alpha-blog/app/views/categories/new.html.erb
<h1 class="text-center mt-4"> Create a new category</h1>
<%= render "form" %>

Section4/alpha-blog/app/views/categories/show.html.erb
<h1 class="text-center mt-4"> <%=@category.name %></h1>


<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
  </div>
<%end %>

<h3  class="text-center mt-4"> Articles</h3>

<div class="flickr_pagination mb-4">
  <div class="page_info">
    <%#= page_entries_info @articles %>
  </div>
  <%= will_paginate(@articles, :container => false) %>
</div>

<% @articles.each do |article| %>
  <%=render "articles/article", article: article %>
<%end%>

<div class="flickr_pagination mb-4">
  <div class="page_info">
    <%#= page_entries_info @articles %>
  </div>
  <%= will_paginate(@articles, :container => false) %>
</div>

Section4/alpha-blog/app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Mashrur Hossain", "https://mashrurhossain.com", class: "text-white" %></small>
  </div>
</footer>

Section4/alpha-blog/app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <% if  name == "notice"%>
      <% classe = "success" %>
    <%else %>
      <% classe= "danger" %>
    <%end %>
    <div class="alert alert-<%=classe %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

Section4/alpha-blog/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <%= link_to "ALPHA BLOG", root_path, class:"navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class:"nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Create New Article", new_article_path, class: "dropdown-item" %>
          <%end %>
          <%= link_to "View Article", articles_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin?%>
            <%= link_to "Create New Category", new_category_path, class: "dropdown-item" %>
          <%end %>
          <%= link_to "View Categories", categories_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <%if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %>Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete your profile", user_path(current_user), class: "dropdown-item text-danger" ,data: {confirm: "Are you sure?"} , method: :delete%>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", logout_path, class:"nav-link ", method: :delete %>
        </li>
        <li class="nav-item">
          <%= link_to current_user.username, user_path(current_user), class:"nav-link ", method: :get %>
        </li>
      <%else %>
        <li class="nav-item">
          <%= link_to "Log in", login_path, class:"nav-link " %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class:"nav-link " %>
        </li>
      <%end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

Section4/alpha-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render "layouts/navigation" %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

Section4/alpha-blog/app/views/shared/_errors.html.erb
<%if obj && obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%=obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <%end%>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<%end %>

Section4/alpha-blog/app/views/users/_form.html.erb
<div class="container">


  <div class="row justify-content-center ">
    <div class="col-10">
      <%= render "shared/errors", obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded" ,local: true) do |f|%>
        <div class="form-group row">
            <%=f.label :username , class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%=f.text_field :username ,class: "form-control shadow rounded", placeholder: "Enter your username"%>
          </div>
        </div>
        <div class="form-group row">
          <%=f.label :email , class: "col-2 col-form-label text-light"%><br/>
          <div class="col-10">
          <%=f.email_field :email ,class: "form-control shadow rounded", placeholder: "Enter your email"%>
          </div>
        </div>
        <div class="form-group row">
          <%=f.label :password , class: "col-2 col-form-label text-light"%><br/>
          <div class="col-10">
            <%=f.password_field :password ,class: "form-control shadow rounded", placeholder: "Enter your password"%>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%=f.submit (@user.new_record? ? "Sign up" : "Update Account") , class:"btn btn-outline-light btn-lg"%>
        </div>
      <%end %>
    </div>
    <div class="mb-3">
      <%= link_to "[Cancel and return to articles listing]", articles_path, class: "text-info"  %>
    </div>
  </div>
</div>

Section4/alpha-blog/app/views/users/_user.html.erb
<div class="row justify-content-center">
  <div class="col-8 ">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header font-italic">
        <%= link_to user.username, user_path(user)%>
      </div>
      <div class="card-body">
        <h5 class="card-title "><%= link_to gravatar_for(user, size:150), user_path(user) %></h5>
        <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
        <%= link_to "View profile", user_path(user), class: "btn btn-outline-success" %>
        <% if logged_in?  %>
          <% if user == current_user %>
            <%= link_to  "Edit Profile", edit_user_path(user.id), method: :get, class: "btn btn-outline-info" %>
            <%end %>
          <% if current_user.admin? %>
            <%= link_to  "Delete Profile", user_path(user.id), method: :delete, class: "btn btn-outline-danger", data: {confirm: "Are you sure you want to delete the user?"}%>
          <%end %>
        <%end %>
      </div>
      <div class="card-footer text-muted">
        <small>Joined <%=time_ago_in_words(user.created_at) %> ago</small>
      </div>
    </div>
  </div>
</div>

Section4/alpha-blog/app/views/users/edit.html.erb
<h1 class="text-center mt-4">
  Edit for Alpha Blog
</h1>
<%=render "users/form" %>

Section4/alpha-blog/app/views/users/index.html.erb
<h1 class="text-center mt-4">
  Alpha Bloggers
</h1>
<div class="flickr_pagination mb-4">
  <div class="page_info">
    <%= page_entries_info @users %>
  </div>
  <%= will_paginate(@users, :container => false) %>
</div>

<% @users.each do |user| %>
  <%= render "users/user", user:user %>
<% end %>

<div class="flickr_pagination mb-4">
  <div class="page_info">
    <%= page_entries_info @users %>
  </div>
  <%= will_paginate(@users, :container => false) %>
</div>

Section4/alpha-blog/app/views/users/new.html.erb
<h1 class="text-center mt-4">
  Sign up for Alpha Blog
</h1>
<%=render "users/form" %>

Section4/alpha-blog/app/views/users/show.html.erb
<h1 class="text-center mt-4">
  <%= @user.username  %> profile
</h1>
<%= gravatar_for(@user, size:200)%>

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
  </div>
<%end %>

<h3  class="text-center mt-4"> Articles</h3>

<div class="flickr_pagination mb-4">
  <div class="page_info">
    <%#= page_entries_info @articles %>
  </div>
  <%= will_paginate(@articles, :container => false) %>
</div>

<% @articles.each do |article| %>
  <%=render "articles/article", article: article %>
<%end%>

<div class="flickr_pagination mb-4">
  <div class="page_info">
    <%#= page_entries_info @articles %>
  </div>
  <%= will_paginate(@articles, :container => false) %>
</div>