finance-tracker/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "welcome#index"
  get "my_portofolio", to: "users#my_portfolio"
  get "search_stock", to: "stocks#search"
  post "users_stock", to: "users_stock#create"
  delete "users_stock", to: "users_stock#destroy"
  get "my_friends", to: "users#my_friends"
  get "search_friend", to: "users#search"
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

finance-tracker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

finance-tracker/app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

finance-tracker/app/models/stock.rb
class Stock < ApplicationRecord

  has_many :user_stocks, dependent: :destroy
  has_many :users, through: :user_stocks
  validates :name, :ticker, presence: true


  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
        publishable_token: Rails.application.credentials.aws[:secret_access_key],
        endpoint: 'https://cloud.iexapis.com/v1'
    )
    begin
      new({ticker: ticker_symbol, name: ticker_symbol , last_price: Stock.calculate_random_price})
    rescue => exception
      return nil
    end
    #return {ticket: ticker_symbol, name: client.company(ticker_symbol).company_name , last_price: client.price(ticker_symbol)}

  end

  def self.check_db(ticker_symbol)
    Stock.where(ticker: ticker_symbol).first
  end

  private
  def self.calculate_random_price
    rand * rand*1000
  end
end

finance-tracker/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_stocks, dependent: :destroy
  has_many :stocks, through: :user_stocks, dependent: :nullify
  has_many :friendships
  has_many :friends, through: :friendships
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    return to_send_back
  end

  def self.matches(field_name,param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def except_current_user(users)
    users.reject{ |user| user.id == self.id}
  end

  def not_firends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end

  def eliminate_friend?(friend_id)
    self.friendships.delete_by(friend_id: friend_id) > 0

  end

end

finance-tracker/app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

finance-tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

finance-tracker/app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend_id = friendship_params
    friend = User.find(friend_id)
    if friend
      current_user.friends << friend
      flash[:notice] = "Following user"
      redirect_to my_friends_path
    else
      flash[:alert] = "There was something wrong with the tracking request"
      render "users/my_friends"
    end
  end

  def destroy
    friend_id = params[:id]
    if current_user.eliminate_friend?(friend_id)
      flash[:notice] = "Stopped following"
      redirect_to my_friends_path
    else
      flash.now[:error] = "Its not possible do that action"
      render "users/my_friends"
    end

  end

  private
  def friendship_params
    params.require(:friend)
  end
end

finance-tracker/app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].present?

      @stock = Stock.new_lookup(params[:stock])
      if @stock
      #@stock = Stock.new(ticker: params[:stock], name: params[:stock], last_price: calculate_random_price)
        respond_to do |format|
          format.js{ render partial: 'users/result'}
        end
      #render "users/my_portfolio", method: :get
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid symbol to search"
          format.js{ render partial: 'users/result'}
        end
        #redirect_to my_portofolio_path
      end
    else
      #flash[:alert] = "Please enter a symbol to search"
      #redirect_to my_portofolio_path
      respond_to do |format|
        flash.now[:alert] = "Please enter a symbol to search"
        format.js{ render partial: 'users/result'}
      end
    end

  end

  private
  def search_params

  end

  def calculate_random_price
    rand * rand*1000
  end
end

finance-tracker/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
    @tracked_stocks = current_user.stocks
    @user = current_user
  end

  def my_friends
    @friends = current_user.friends
  end

  def search
    if params[:friend].present?
      name = params[:friend]
      @friends = User.search(name)
      @friends = current_user.except_current_user(@friends) if @friends
      #@friends.delete(current_user) if @friends
      if @friends
        respond_to do |format|
          format.js{render partial: "users/friend_result"}
        end
      else
        respond_to do |format|
          flash[:alert] = "Couldn't find user"
          format.js{render partial: "users/friend_result"
          }
        end
      end
    else
      respond_to do |format|
        flash[:alert] = "Please enter a friend name or email to search"
        format.js{render partial: "users/friend_result"
        }
      end
    end
  end

  def show
    friend_id = params[:id]
    @user = User.find(friend_id)
    @tracked_stocks = @user.stocks
    unless @user
      flash[:error] = "Problem with finding User Profile"
      redirect_to root_path
    end

  end

end

finance-tracker/app/controllers/users_stock_controller.rb
class UsersStockController < ApplicationController

  def create
    stock = Stock.check_db(params[:ticker])
    if !stock
      stock = Stock.new_lookup(params[:ticker])
      if stock != nil
       stock.save
      end
    end
    if stock
        UserStock.create(user_id:params[:user], stock_id: stock.id)
        flash[:notice] = "Added successfully to your portfolio"
        redirect_to my_portofolio_path
    else
        flash.now[:alert] = "Erro"
        render "users/my_portfolio"

    end
  end


  def destroy
    if params[:stock_id].present?
      current_user.user_stocks.where(stock_id: params[:stock_id]).each do |s|
        s.destroy
      end
    end
    redirect_to my_portofolio_path
  end


end

finance-tracker/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

finance-tracker/app/helpers/application_helper.rb
module ApplicationHelper
end

finance-tracker/app/helpers/friendships_helper.rb
module FriendshipsHelper
end

finance-tracker/app/helpers/stocks_helper.rb
module StocksHelper
end

finance-tracker/app/helpers/users_helper.rb
module UsersHelper
end

finance-tracker/app/helpers/users_stock_helper.rb
module UsersStockHelper
end

finance-tracker/app/helpers/welcome_helper.rb
module WelcomeHelper
end

finance-tracker/app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
      <% @friends.each do |friend| %>
      <tr class="mt-5 mb-5">
        <td><strong> Email: </strong><%= friend.email%></td>
        <td> <strong> Name: </strong><%= friend.full_name%></td>
        <td>
          <strong> Actions: </strong><%= link_to "View Profile", user_path(friend), class: "btn btn-sm btn-success"%>
          <% if current_user.not_firends_with?(friend.id) %>
          <%= link_to "Follow friend", friendships_path(friend: friend), class: "btn btn-sm btn-success", method: :post %>
          <%else %>
            <span class="badge badge-secondary"> You are friends</span>
          <%end %>
        </td>
      </tr>
      <%end %>
    </tbody>
  </table>
</div>

finance-tracker/app/views/users/_friend_result.js.erb
document.querySelector("#my_friends").innerHTML = '<%= escape_javascript( render 'users/friend_result.html') %>';

finance-tracker/app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>
<%if @stock %>
  <div class="card card-header results-block">
    <strong> Symbol: </strong><%= @stock.ticker%>
    <strong> Name: </strong><%= @stock.name%>
    <strong> Price: </strong><%= @stock.last_price%>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to "Add to Portfolio", users_stock_path(user: current_user, ticker: @stock.ticker), method: :post, class: "btn btn-xs btn-success" %>
    <%else %>
      <span class="badge badge-secondary">
        You are already tracking
        <% if !current_user.under_stock_limit? %>
          10 stocks
        <%end %>
        <%if current_user.stock_already_tracked?(@stock.ticker) %>
          this stock
        <%end %>
      </span>
    <%end %>
  </div>
<%end %>

finance-tracker/app/views/users/_result.js.erb
document.querySelector("#results").innerHTML = '<%= escape_javascript( render 'users/result.html') %>'

finance-tracker/app/views/users/my_friends.html.erb
<h1>Friends</h1>
<div class="search-area">
  <h3>Search Stocks</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag "friend", params[:friend], placeholder: "Friend email", autofocus: true, class: "form-control form-control-lg"%>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do%>
          <%= fa_icon 'search' %>
        <%end %>
      </div>
    </div>
  <%end %>
</div>

<div id="my_friends">
</div>
<% if !@friends.empty? %>
  <%= render "friends/list" %>
<%end %>

finance-tracker/app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>

<div class="search-area">
  <h3>Search Stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag "stock", params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg"%>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do%>
          <%= fa_icon 'search' %>
        <%end %>
      </div>
    </div>
  <%end %>
</div>
<div id="results">
  <%= render "users/result" %>
</div>

finance-tracker/app/views/users/show.html.erb
<h1>User Details</h1>


<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td><strong> Email: </strong><%= @user.email%></td>
        <td> <strong> Name: </strong><%= @user.full_name%></td>
        <td>
          <% if current_user.not_firends_with?(@user.id) %>
            <%= link_to "Follow friend", friendships_path(friend: @user), class: "btn btn-sm btn-success", method: :post %>
          <%else %>
            <span class="badge badge-secondary"> You are friends</span>
          <%end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<% if !@tracked_stocks.empty? %>
  <%=render "stocks/list"%>
<%end %>

finance-tracker/app/views/welcome/index.html.erb
<h1>Welcome to the Finance Tracker app</h1>
<p></p>
<%= link_to "Logout", destroy_user_session_path, method: :delete %>